name: Keep n8n Alive
on:
  schedule:
    - cron: '*/7 * * * *'  # Runs every 7 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping n8n
        run: curl -s https://n8n-render-vd06.onrender.com/healthz
